t1:
	strDebug.pl --file=test1.c && gcc -o ./test1_O ./test1.c && ./test1_O
t2:
	strDebug.pl --file=test2.c && gcc -o ./test2_O ./test2.c && ./test2_O
t3:
	strDebug.pl --file=test3.c && gcc -o ./test3_O ./test3.c && ./test3_O
