all: compile run catr catw
compile:
	gcc -o ./arrLess_O arrLess.c
clear:
	rm ./feof_O
run:
	./arrLess_O
catr:
	cat ./arrLess_r.txt
catw:
	cat ./arrLess_w.txt
vim:
	vim ./shitWorks.c
vimr:
	vim ./_r.txt
vimw:
	vim ./shitWorks_w.txt
echow:
	echo "fuck" > shitWorks_w.txt
